sudo: required
language: generic 
services: 
  - docker

before_install:
  - docker build -t miteshthakor1996/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true miteshthakor1996/docker-react npm run test